troy:
  task:
    accessToken:
    admin:
      addresses: https://10.0.0.116:19999/troy-task-admin
    executor:
      appname: troy-trade-ws-task
      ip:
      port: 0
      logpath: ${logging.path}/xxl-job/jobhandler
      logretentiondays: -1